import React, { useState } from 'react';
import { AlertTriangle, ShieldAlert, Search, Filter, ExternalLink, Eye, Network } from 'lucide-react';

export default function AlertsView({ alerts = [], onSelectAlert, onViewGraphTarget, onSelectTx }) {
  const [searchTerm, setSearchTerm] = useState('');
  const [severityFilter, setSeverityFilter] = useState('ALL');
  const [sourceFilter, setSourceFilter] = useState('ALL');

  const alertsList = alerts && alerts.length > 0 ? alerts : [];

  const filtered = alertsList.filter((a) => {
    const matchesSearch = 
      (a.alert_id || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
      (a.target_id || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
      (a.rule_name || a.alert_type || '').toLowerCase().includes(searchTerm.toLowerCase());

    let matchesSeverity = true;
    const score = a.prioritization_score || a.risk_score || 0;
    if (severityFilter === 'HIGH') matchesSeverity = score >= 75;
    else if (severityFilter === 'MEDIUM') matchesSeverity = score >= 45 && score < 75;
    else if (severityFilter === 'LOW') matchesSeverity = score < 45;

    let matchesSource = true;
    const src = a.detection_source || a.source || 'Isolation Forest';
    if (sourceFilter !== 'ALL') matchesSource = src.toLowerCase().includes(sourceFilter.toLowerCase());

    return matchesSearch && matchesSeverity && matchesSource;
  });

  const getSeverityBadge = (score) => {
    if (score >= 75) {
      return (
        <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-rose-500/20 text-rose-400 border border-rose-500/40 uppercase">
          HIGH ({score.toFixed(0)})
        </span>
      );
    }
    if (score >= 45) {
      return (
        <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-amber-500/20 text-amber-400 border border-amber-500/40 uppercase">
          MEDIUM ({score.toFixed(0)})
        </span>
      );
    }
    return (
      <span className="px-2 py-0.5 rounded text-[10px] font-semibold bg-emerald-500/20 text-emerald-400 border border-emerald-500/40 uppercase">
        LOW ({score.toFixed(0)})
      </span>
    );
  };

  return (
    <div className="p-6 space-y-6 max-w-[1600px] mx-auto font-mono">
      
      {/* Header Controls */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-[#0B1626] border border-[#101C2E] p-4 rounded-xl">
        <div>
          <h2 className="text-sm font-bold text-white uppercase tracking-wider flex items-center space-x-2">
            <AlertTriangle className="w-4 h-4 text-[#F59E0B]" />
            <span>Active Security & Anomaly Alerts</span>
          </h2>
          <p className="text-[11px] text-slate-400">Real-time alerts generated by Isolation Forest, DBSCAN & Graph heuristics</p>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          
          {/* Search */}
          <div className="relative w-56">
            <Search className="w-3.5 h-3.5 absolute left-3 top-2.5 text-slate-500" />
            <input
              type="text"
              placeholder="Search Alert / Target ID..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full bg-[#050B14] text-xs text-cyan-300 placeholder-slate-500 pl-8 pr-3 py-1.5 rounded-xl border border-[#101C2E] focus:outline-none focus:border-[#2196F3]"
            />
          </div>

          {/* Severity Filter */}
          <select
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            className="bg-[#050B14] text-xs text-slate-300 py-1.5 px-3 rounded-xl border border-[#101C2E] focus:outline-none"
          >
            <option value="ALL">All Severities</option>
            <option value="HIGH">High Severity (&gt; 75)</option>
            <option value="MEDIUM">Medium Severity (45-75)</option>
            <option value="LOW">Low Severity (&lt; 45)</option>
          </select>

          {/* Source Filter */}
          <select
            value={sourceFilter}
            onChange={(e) => setSourceFilter(e.target.value)}
            className="bg-[#050B14] text-xs text-slate-300 py-1.5 px-3 rounded-xl border border-[#101C2E] focus:outline-none"
          >
            <option value="ALL">All Detection Sources</option>
            <option value="isolation">Isolation Forest</option>
            <option value="dbscan">DBSCAN</option>
            <option value="heuristic">Graph Heuristics</option>
          </select>

        </div>
      </div>

      {/* Alerts Table */}
      <div className="bg-[#0B1626] border border-[#101C2E] rounded-xl overflow-hidden shadow-md">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-[#050B14] text-slate-400 border-b border-[#101C2E] uppercase text-[10px]">
              <tr>
                <th className="py-3 px-4">Alert ID</th>
                <th className="py-3 px-4">Severity</th>
                <th className="py-3 px-4">Alert Type / Rule</th>
                <th className="py-3 px-4">Target Entity / TXID</th>
                <th className="py-3 px-4">Source Engine</th>
                <th className="py-3 px-4">Evidence Summary</th>
                <th className="py-3 px-4">Status</th>
                <th className="py-3 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#101C2E]">
              {filtered.map((alert) => {
                const score = alert.prioritization_score || alert.risk_score || 0;
                const targetId = alert.target_id || alert.txid || 'TX_unknown';
                const ruleName = alert.rule_name || alert.alert_type || 'Peeling Chain Anomaly';
                const engine = alert.detection_source || 'Isolation Forest ML';
                const evidence = alert.evidence_summary || alert.details || 'High structural feature anomaly detected on-chain.';
                const status = alert.status || 'OPEN';

                return (
                  <tr key={alert.alert_id || Math.random()} className="hover:bg-[#101C2E]/50 transition">
                    <td className="py-3 px-4 font-bold text-amber-400">{alert.alert_id || 'ALT-8902'}</td>
                    <td className="py-3 px-4">{getSeverityBadge(score)}</td>
                    <td className="py-3 px-4 text-slate-200 font-semibold">{ruleName}</td>
                    <td className="py-3 px-4 text-cyan-300 font-bold break-all max-w-xs">
                      {targetId.substring(0, 22)}...
                    </td>
                    <td className="py-3 px-4 text-slate-400 text-[11px]">
                      <span className="px-2 py-0.5 rounded bg-[#050B14] border border-[#101C2E] text-slate-300">
                        {engine}
                      </span>
                    </td>
                    <td className="py-3 px-4 text-slate-300 text-[11px] max-w-sm truncate">{evidence}</td>
                    <td className="py-3 px-4">
                      <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-[#2196F3]/20 text-[#2196F3] border border-[#2196F3]/40">
                        {status}
                      </span>
                    </td>
                    <td className="py-3 px-4 text-right">
                      <div className="flex items-center justify-end space-x-1.5">
                        
                        {/* View Evidence */}
                        <button
                          onClick={() => onSelectAlert && onSelectAlert(alert)}
                          className="px-2 py-1 bg-[#101C2E] hover:bg-[#2196F3] text-slate-300 hover:text-white rounded border border-slate-700/50 text-[10px] font-bold flex items-center space-x-1"
                          title="Inspect Evidence Lineage"
                        >
                          <Eye className="w-3 h-3" />
                          <span>Evidence</span>
                        </button>

                        {/* View Graph */}
                        {onViewGraphTarget && (
                          <button
                            onClick={() => onViewGraphTarget(targetId)}
                            className="px-2 py-1 bg-[#101C2E] hover:bg-emerald-600 text-slate-300 hover:text-white rounded border border-slate-700/50 text-[10px] font-bold flex items-center space-x-1"
                            title="Explore Subgraph"
                          >
                            <Network className="w-3 h-3" />
                            <span>Graph</span>
                          </button>
                        )}

                        {/* View Transaction */}
                        {onSelectTx && (
                          <button
                            onClick={() => onSelectTx({ txid: targetId.replace('TX_', ''), risk_score: score })}
                            className="px-2 py-1 bg-[#101C2E] hover:bg-amber-600 text-slate-300 hover:text-white rounded border border-slate-700/50 text-[10px] font-bold flex items-center space-x-1"
                            title="Inspect Transaction"
                          >
                            <ExternalLink className="w-3 h-3" />
                            <span>TX</span>
                          </button>
                        )}

                      </div>
                    </td>
                  </tr>
                );
              })}

              {filtered.length === 0 && (
                <tr>
                  <td colSpan="8" className="py-8 text-center text-slate-500">
                    No active alerts found for the current dataset scope.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
}
